# Generated by Django 3.0 on 2019-12-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='DETAIL',
            field=models.CharField(default='base', max_length=120, verbose_name='Detail'),
        ),
    ]
