# Generated by Django 3.0 on 2019-12-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20191213_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinfo',
            name='DETAIL',
        ),
    ]
